apiVersion: v1
kind: Service
metadata:
  name: api-service-1
  namespace: delivery
spec:
  selector:
    app: api-produtos
    instance: "1"
  ports:
    - port: 5000
      targetPort: 5000
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: api-service-2
  namespace: delivery
spec:
  selector:
    app: api-produtos
    instance: "2"
  ports:
    - port: 5001
      targetPort: 5000
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: api-service-3
  namespace: delivery
spec:
  selector:
    app: api-produtos
    instance: "3"
  ports:
    - port: 5002
      targetPort: 5000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-produtos-1
  namespace: delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-produtos
      instance: "1"
  template:
    metadata:
      labels:
        app: api-produtos
        instance: "1"
    spec:
      containers:
        - name: api
          image: andrearms/api-produtos:v2
          env:
            - name: DB_HOST
              value: postgres-service.delivery.svc.cluster.local
            - name: DB_USER
              value: admin
            - name: DB_PASSWORD
              value: admin123
            - name: DB_NAME
              value: produtosdb
          ports:
            - containerPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-produtos-2
  namespace: delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-produtos
      instance: "2"
  template:
    metadata:
      labels:
        app: api-produtos
        instance: "2"
    spec:
      containers:
        - name: api
          image: andrearms/api-produtos:v2
          env:
            - name: DB_HOST
              value: postgres-service.delivery.svc.cluster.local
            - name: DB_USER
              value: admin
            - name: DB_PASSWORD
              value: admin123
            - name: DB_NAME
              value: produtosdb
          ports:
            - containerPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-produtos-3
  namespace: delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-produtos
      instance: "3"
  template:
    metadata:
      labels:
        app: api-produtos
        instance: "3"
    spec:
      containers:
        - name: api
          image: andrearms/api-produtos:v2
          env:
            - name: DB_HOST
              value: postgres-service.delivery.svc.cluster.local
            - name: DB_USER
              value: admin
            - name: DB_PASSWORD
              value: admin123
            - name: DB_NAME
              value: produtosdb
          ports:
            - containerPort: 5000